export enum NotificationType {
  // Citas
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',

  // Clientes
  CLIENT_ASSIGNED = 'CLIENT_ASSIGNED',
  CLIENT_CONVERSION_CONFIRMED = 'CLIENT_CONVERSION_CONFIRMED',
  CLIENT_CONVERSION_REJECTED = 'CLIENT_CONVERSION_REJECTED',

}